# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3log', '0004_s3accesslog2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s3accesslog2',
            name='request_key',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='s3accesslog2',
            name='request_uri',
            field=models.CharField(max_length=2048),
        ),
    ]
