# Generated by Django 2.2.2 on 2019-06-07 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s3accesslog',
            name='http_status',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s3accesslog',
            name='remote_ip',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='s3accesslog',
            name='request_id',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
