# Generated by Django 2.2.2 on 2019-06-07 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_auto_20190607_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s3accesslog',
            name='bucket_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='s3accesslog',
            name='bucket_owner',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='s3accesslog',
            name='bytes_sent',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s3accesslog',
            name='error_code',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='s3accesslog',
            name='object_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s3accesslog',
            name='operation',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='s3accesslog',
            name='referrer',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='s3accesslog',
            name='request_datetime',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='s3accesslog',
            name='request_id',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='s3accesslog',
            name='requesta',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='s3accesslog',
            name='total_time',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s3accesslog',
            name='turn_around_time',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='s3accesslog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='s3accesslog',
            name='version_id',
            field=models.CharField(max_length=128),
        ),
    ]
