# Generated by Django 2.2.2 on 2019-06-07 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_auto_20190607_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s3accesslog',
            name='version_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
